#!/usr/bin/env bash


function filesum () {

    echo $(md5sum ${1} | grep -oP "^.{32}")

}

DUMBER=${HOME}/go/bin/dumber
RIGHT_NUMBERED_SECTIONS_CHECKSUM=a60c33256a196cf50bc7b9b5f1d5927c
RIGHT_NUMBERED_SECTIONS_WITH_TOC_CHECKSUM=97e935c8c60905c4da05a82236f49cd1

echo

# Numbering Markdown sections test
${DUMBER} test/test.md > test/numbered-sections.md

echo -n "- Numbering Markdown sections                    -> "

if  [ "$(filesum "test/numbered-sections.md")" == "$RIGHT_NUMBERED_SECTIONS_CHECKSUM" ]; then
    echo "OK"
else
    echo "KO"
fi


# Unnumbering Markdown sections test
${DUMBER} -r test/numbered-sections.md > test/unnumbered-sections.md

echo -n "- Unnumbering Markdown sections                  -> "

if  [ "$(filesum "test/unnumbered-sections.md")" == "$(filesum "test/test.md")" ]; then
    echo "OK"
else
    echo "KO"
fi

# Numbering Markdown sections with toc test
${DUMBER} -t test/test.md > test/numbered-sections-with-toc.md

echo -n "- Numbering Markdown sections and adding toc     -> "

if  [ "$(filesum "test/numbered-sections-with-toc.md")" == "$RIGHT_NUMBERED_SECTIONS_WITH_TOC_CHECKSUM" ]; then
    echo "OK"
else
    echo "KO"
fi

# Unnumbering Markdown sections and removing toc test
${DUMBER} -r test/numbered-sections-with-toc.md > test/unnumbered-sections-removed-toc.md

echo -n "- Unnumbering Markdown sections and removing toc -> "

if  [ "$(filesum "test/unnumbered-sections-removed-toc.md")" == "$(filesum "test/test.md")" ]; then
    echo "OK"
else
    echo "KO"
fi

